In [30]:
import numpy as np

In [31]:
def Gauss_Seidel(A, b, x, n):
    """
    Computes x vector from Ax=b linear matrix equation
    """
    
    L = np.tril(A)    # L is strictly lower triangluar matrix
    U = A - L         # U is upper triangulat matrix
    
    for i in range(n):
        x_new = np.dot(np.linalg.inv(L), b - np.dot(U, x))
        
        if np.all((abs(x_new-x)<=1e-8)):
            break
        #print str(i).zfill(3),
        
        x = x_new
        print(x)
    
    return x

In [34]:
A = np.array([[1.0, 2.0, 0, 0], [0, 3.0, 4.0, 0], [0, 0, -2, 1], [1, 2, 3, 4]])
b = [5, 6, 7, 8]
x = [1, 1, 1, 1]

In [36]:
Gauss_Seidel(A, b, x, 1000)

[ 3.          0.66666667 -3.          3.16666667]
[ 3.66666667  6.         -1.91666667 -0.47916667]
[-7.          4.55555556 -3.73958333  4.27690972]
[-4.11111111  6.98611111 -1.36154514  0.55588108]
[-8.97222222  3.81539352 -3.22205946  4.75190339]
[-2.63078704  6.29607928 -1.1240483   0.35269335]
[-7.59215856  3.49873107 -3.32365333  4.6414141 ]
[-1.99746214  6.43153777 -1.17929295  0.16806636]
[-7.86307554  3.5723906  -3.41596682  4.7415487 ]
[-2.1447812   6.55462242 -1.12922565  0.10580333]
[-8.10924485  3.5056342  -3.44709834  4.85981786]
[-2.0112684   6.59613112 -1.07009107  0.00731984]
[-8.19226223  3.42678809 -3.49634008  4.95692657]
[-1.85357618  6.66178677 -1.02153671 -0.10134681]
[-8.32357354  3.36204895 -3.5506734   5.06287396]
[-1.7240979   6.7342312  -0.96856302 -0.20966886]
[-8.46846241  3.29141736 -3.60483443  5.17503275]
[-1.58283472  6.80644591 -0.91248363 -0.32315155]
[-8.61289182  3.21664484 -3.66157578  5.29108237]
[-1.43328967  6.88210104 -0.85445882 -0.44188399]


array([  2.85836070e+09,   1.45936912e+09,   1.11764667e+09,
        -2.28250973e+09])